/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class OnNatDetectionCompleteParam {
    protected transient boolean swigCMemOwn;
    private transient long swigCPtr;

    protected OnNatDetectionCompleteParam(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    public OnNatDetectionCompleteParam() {
        this(pjsua2JNI.new_OnNatDetectionCompleteParam(), true);
    }

    protected static long getCPtr(OnNatDetectionCompleteParam obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                pjsua2JNI.delete_OnNatDetectionCompleteParam(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public int getStatus() {
        return pjsua2JNI.OnNatDetectionCompleteParam_status_get(swigCPtr, this);
    }

    public void setStatus(int value) {
        pjsua2JNI.OnNatDetectionCompleteParam_status_set(swigCPtr, this, value);
    }

    public String getReason() {
        return pjsua2JNI.OnNatDetectionCompleteParam_reason_get(swigCPtr, this);
    }

    public void setReason(String value) {
        pjsua2JNI.OnNatDetectionCompleteParam_reason_set(swigCPtr, this, value);
    }

    public pj_stun_nat_type getNatType() {
        return pj_stun_nat_type.swigToEnum(pjsua2JNI.OnNatDetectionCompleteParam_natType_get(swigCPtr, this));
    }

    public void setNatType(pj_stun_nat_type value) {
        pjsua2JNI.OnNatDetectionCompleteParam_natType_set(swigCPtr, this, value.swigValue());
    }

    public String getNatTypeName() {
        return pjsua2JNI.OnNatDetectionCompleteParam_natTypeName_get(swigCPtr, this);
    }

    public void setNatTypeName(String value) {
        pjsua2JNI.OnNatDetectionCompleteParam_natTypeName_set(swigCPtr, this, value);
    }

}
